### ISSUE TITLE
v1.0.0 is not work (v0.03 is ok)

### ISSUE THREAD

**Issue by komikoni** [juanjoDiaz/removeNPMAbsolutePaths#4]

**Comment by juanjoDiaz** [comment]
Hi @komikoni,

Can you elaborate a bit on what's not working please?

**Comment by komikoni** [comment]
Hi @juanjoDiaz 

Sorry, I forgot the main text.

Thank you very much for your useful tools.
I am using removeNPMAbsolutePaths when building for Lambda. The reason is to prevent unnecessary information from entering the built Zip.

Currently, in my environment, 1.0.0 results in a syntax error as follows.
In 0.0.3, it works without problems.

```
komikoni@MY-PC1 MINGW64 ~/workspace/sample
$ npm install -g removeNPMAbsolutePaths
C:\Users\komikoni\AppData\Roaming\npm\removeNPMAbsolutePaths -> C:\Users\komikoni\AppData\Roaming\npm\node_modules\removeNPMAbsolutePaths\bin\removeNPMAbso
lutePaths
C:\Users\komikoni\AppData\Roaming\npm
`-- removeNPMAbsolutePaths@1.0.0


komikoni@MY-PC1 MINGW64 ~/workspace/sample
$ removeNPMAbsolutePaths .
C:\Users\komikoni\AppData\Roaming\npm\node_modules\removeNPMAbsolutePaths\src\removeNPMAbsolutePaths.js:78
    );
    ^
SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\komikoni\AppData\Roaming\npm\node_modules\removeNPMAbsolutePaths\bin\removeNPMAbsolutePaths:7:32)

komikoni@MY-PC1 MINGW64 ~/workspace/sample
$ node -v
v6.10.3

komikoni@MY-PC1 MINGW64 ~/workspace/sample
$ npm -v
3.10.10

komikoni@MY-PC1 MINGW64 ~/workspace/sample
$ bash --version
GNU bash, version 4.4.12(1)-release (x86_64-pc-msys)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by juanjoDiaz** [comment]
Version 1.0.2 should fix your issue. Please re-open this if it doesn't :)
